server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.27:3306/studydb?serverTimezone=UTC&characterEncoding=UTF-8
    username: study
    password: study
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jwt:
  secret-key: S3cr3tK3y
