server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.27:3306/studydb?serverTimezone=UTC&characterEncoding=UTF-8
    username: study
    password: study
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-exclude: static/**,public/**

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
jwt:
  secret-key: S3cr3tK3y

springdoc:
  api-docs:
    path: /sw-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swtest # swagger-ui 접근 경로에 대한 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션 됨.
    groups-order: ASC # path, query, body, response 순으로 출력
    tags-sorter: alpha # 태그를 알파벳 순으로 정렬
    operations-sorter: method  # delete - get - patch - post - put 순으로 정렬, alpha를 사용하면 알파벳 순으로 정렬 가능
    doc-expansion: true # swagger tag 리스트 펼치기
  paths-to-match: /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴

